#!/bin/sh



#### KEYBINDINGS #######################
# Apps
riverctl map normal Super Return spawn foot
riverctl map normal Super E spawn thunar
riverctl map normal Super F spawn firefox
riverctl map normal Super G spawn thunderbird
riverctl map normal Super P spawn "wmenu-run -i -f 'CaskaydiaCove Nerd Font Propo 17'"
riverctl map normal Super T spawn Telegram
riverctl map normal Super W spawn wasistlos
riverctl map normal Super+Shift E spawn emacs
riverctl map normal Super+Shift R spawn readpdf-wayland.sh
riverctl map normal Super+Control L spawn "swaylock -c=#222222"

# window management
riverctl map normal Super+Shift C close
riverctl map normal Super+Shift Q exit

riverctl map normal Super Tab focus-previous-tags
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl map normal Super+Shift Return zoom
riverctl map normal Super O toggle-float
riverctl map normal Super M toggle-fullscreen

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal Super D send-layout-cmd rivertile "main-count +1"
riverctl map normal Super I send-layout-cmd rivertile "main-count -1"

riverctl map normal Super Left move left 100
riverctl map normal Super Down move down 100
riverctl map normal Super Up move up 100
riverctl map normal Super Right move right 100

riverctl map normal Super+Control Left snap left
riverctl map normal Super+Control Down snap down
riverctl map normal Super+Control Up snap up
riverctl map normal Super+Control Right snap right

riverctl map normal Super+Shift Left resize horizontal -100
riverctl map normal Super+Shift Down resize vertical 100
riverctl map normal Super+Shift Up vertical -100
riverctl map normal Super+Shift Right resize horizontal 100

# MOUSE
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad tap enabled
riverctl focus-follows-cursor normal

# TAGS

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
riverctl border-color-focused 0x005577
riverctl border-color-unfocused 0xaaaaaa
riverctl border-width 4

# Set keyboard repeat rate
riverctl set-repeat 30 400

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'thunar' float
riverctl rule-add -app-id 'wasistlos' tags $((1 << 8))
riverctl rule-add -app-id 'org.telegram.desktop' tags $((1 << 8))
riverctl rule-add -app-id 'org.mozilla.Thunderbird' tags $((1 << 7))

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 -main-ratio 0.55 &

# STARTUP APPS
riverctl spawn "waybar"
riverctl spawn "nm-applet"
riverctl spawn "dunst"
riverctl spawn "blueman-applet"
riverctl spawn "swaybg --mode=stretch --image=${HOME}/Pictures/Wallpaperx/river.jpg"
