add_newline = false
format = '''$python[\[](red)$username@$hostname $directory[\]](red)$os '''
right_format = "$git_branch$git_metrics$git_status"

[username]
disabled = false
show_always = true
format = "[$user](bold yellow)"

[hostname]
ssh_symbol = " "
ssh_only = false
format = "[$hostname](bold blue)"

[character]
success_symbol = '[\$](white)'
error_symbol = '[\$](white)'

[cmd_duration]
disabled = true

[directory]
read_only = " 󰌾"
truncation_length = 1
truncate_to_repo = true
format = "[$path](purple)"

####### GIT #######

[git_branch]
symbol = " "
always_show_remote = true
format = " [$symbol( $remote_name)]($style)"

[git_metrics]
disabled = false
format = " ([+$added]($added_style))([-$deleted]($deleted_style) )"

[git_status]
diverged = '[\($count⇕ \)](green)'
ahead = '[\($count⇡ \)](green)'
behind = '[\($count⇣ \)](green)'
untracked = '[\($count?\)](blue)'
modified = '[\($count!\)](yellow)'
stashed = '[\($count \$\)](green)'
staged = '[\($count+\)](green)'
deleted = '[\($count✘ \)](red)'

[python]
format = '(\($virtualenv\))'

####### OS #######

[os]
disabled = false

[os.symbols]
Alpaquita = ""
Alpine = ""
AlmaLinux = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Redox = "󰀘"
Solus = "󰠳"
SUSE = ""
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"

[package]
disabled = true
